const jobs = [
    {
      id:1,
      imagen:"Intexus",
      puesto: "Gerente Comercial de Cuenta",
      empresa: "Intexus",
      ciudad: "Bogotá",
      salario: "$ 2M - 3M COP",
      numVacante: "1",
      fecha: "16 minutos",
      remoto: true,
      ingles: true,
      capacitaciones: false,
      flexible: true,
    },
    {
      id:2,
      imagen:"Polittan",
      puesto: "Lider Técnico",
      empresa: "Polittan",
      ciudad: "Remoto",
      salario: "Confidencial",
      numVacante: "1",
      fecha: "4 días",
      remoto: true,
      ingles: true,
      capacitaciones: false,
      flexible: true,
    },
    {
      id:3,
      imagen:"Queo",
      puesto: "Generador de Demanda",
      empresa: "Queo",
      ciudad: "Remoto",
      salario: "$ 2M COP",
      numVacante: "3",
      fecha: "4 días",
      remoto: true,
      ingles: true,
      capacitaciones: false,
      flexible: true,
    },
    {
      id:4,
      imagen:"Offiemedicas",
      puesto: "Auxiliar de Farmacia",
      empresa: "OFFIMEDICAS",
      ciudad: "Palmira",
      salario: "$ 1.4M COP",
      numVacante: "1",
      fecha: "5 días",
      remoto: true,
      ingles: true,
      capacitaciones: false,
      flexible: true,
    },
    {
      id:5,
      imagen:"Edulabs",
      puesto: "Director Comercial de Software",
      empresa: "EDU LABS S.A.S",
      ciudad: "Remoto",
      salario: "$ 3.5M COP",
      numVacante: "1",
      fecha: "5 días",
      remoto: true,
      ingles: true,
      capacitaciones: false,
      flexible: true,
    },
    {
      id:6,
      imagen:"Metf",
      puesto: "Ejecutivo Master en Protección",
      empresa: "Metlife Medellín",
      ciudad: "Hibrido - Medellín",
      salario: "$ 6M COP",
      numVacante: "1",
      fecha: "6 días",
      remoto: true,
      ingles: true,
      capacitaciones: false,
      flexible: true,
    },
  ]

  export { jobs }